      
         const botResponses = {
  "hi": "Hello! How can I assist you today?",
  "hello": "Hi, How I can help you!!",
  "can we become friend": "Yes",
  "how are you": "I'm just a bot, but I'm doing great! How about you?",
  "what is your name?": "I’m ChatBot, your virtual assistant.",
  "who made you": "I was created by developers to help answer your questions.",
  "tell me a joke": "Why don’t skeletons fight each other? They don’t have the guts!",
  "what is the time": "I can’t see a clock, but your device should know.",
  "bye": "Goodbye! Have a great day.",
  "thank you": "You’re welcome!",
  "i love you": "That’s sweet! I’m here to help you anytime.",
  "where are you from": "I live in the cloud — no rent, no bills!",
  "what can you do": "I can chat with you, answer questions, and keep you company.",

  "what is python": "Python is a high-level, interpreted programming language known for simplicity and versatility.\n• Easy to read/write due to clean syntax (similar to English)\n• Dynamically typed and supports multiple paradigms (OOP, functional, procedural)\n• Extensive libraries for AI, data science, web, automation\n• Example: Used in Google, YouTube, Instagram, and machine learning applications",

  "what is java?": "Java is a platform-independent, object-oriented programming language.\n• Famous for 'Write Once, Run Anywhere' due to JVM (Java Virtual Machine)\n• Used in enterprise systems, Android development, cloud apps\n• Provides features like garbage collection, strong memory management\n• Example: Banking systems, Android apps, large-scale enterprise applications",

  "what is recursion": "Recursion is when a function calls itself to solve smaller parts of a problem.\n• Useful for problems that can be divided into subproblems (divide-and-conquer)\n• Requires a base condition to stop infinite looping\n• Commonly used in: factorial calculation, Fibonacci sequence, tree/graph traversal",

  "who is prime minister of india?": "Narendra Modi is the Prime Minister of India since May 2014.\n• Belongs to Bharatiya Janata Party (BJP)\n• Represents Varanasi constituency\n• Key initiatives: Digital India, Startup India, Swachh Bharat, Make in India",

  "what is g20": "The G20 (Group of Twenty) is an intergovernmental forum of 19 countries + the European Union.\n• Founded in 1999 to address global financial stability\n• Members include India, USA, China, Japan, EU, etc.",

  "tell me about yourself": "This is usually the first interview question.\nStructure:\n• Start with a brief intro\n• Highlight your skills\n• Share achievements\n• Conclude with enthusiasm for the role",

  "why should we hire you": "Emphasize skills matching job requirements, enthusiasm, and cultural fit.\nExample: 'I bring strong coding skills in Python/SQL, proven problem-solving ability, and adaptability.'",

  "what is leadership": "Leadership is the ability to inspire and guide others toward achieving goals.\n• Traits: vision, communication, accountability, decision-making",

  "who is virat kohli": "Virat Kohli is one of India’s greatest batsmen and former captain.\n• Known for consistency, fitness, and aggressive play",

  "what is ipl": "The Indian Premier League (IPL) is a professional T20 cricket league started in 2008.\n• Combines cricket + entertainment\n• Example: CSK & MI are top teams",

  // 🔥 New 50 Q&A
  "what is ai": "AI (Artificial Intelligence) is the simulation of human intelligence in machines. Used in chatbots, self-driving cars, recommendations, etc.",
  "what is machine learning": "ML is a subset of AI where machines learn patterns from data and improve performance without being explicitly programmed.",
  "what is data science": "Data Science combines statistics, programming, and domain knowledge to extract insights and make predictions from data.",
  "what is cloud computing": "Cloud computing delivers services like servers, storage, and databases over the internet. Examples: AWS, Azure, Google Cloud.",
  "what is blockchain": "Blockchain is a distributed ledger technology used for secure, transparent transactions. Basis of Bitcoin & cryptocurrencies.",
  "what is cryptocurrency": "Cryptocurrency is a digital currency secured by cryptography. Examples: Bitcoin, Ethereum.",
  "what is github": "GitHub is a platform for version control and collaboration using Git.",
  "what is html": "HTML (HyperText Markup Language) is the standard language for structuring web pages.",
  "what is css": "CSS (Cascading Style Sheets) styles the layout and design of HTML web pages.",
  "what is javascript": "JavaScript is a scripting language used to make web pages interactive.",
  "what is react": "React is a JavaScript library for building fast, dynamic user interfaces.",
  "what is nodejs": "Node.js is a runtime environment that lets you run JavaScript on the server side.",
  "what is mongodb": "MongoDB is a NoSQL database that stores data in flexible JSON-like documents.",
  "what is sql": "SQL (Structured Query Language) is used to manage and query relational databases.",
  "what is api": "API (Application Programming Interface) allows different software systems to communicate.",
  "what is rest api": "REST API is an architectural style for designing networked applications using HTTP requests.",
  "what is oop": "OOP (Object-Oriented Programming) organizes code into classes and objects. Principles: Encapsulation, Abstraction, Inheritance, Polymorphism.",
  "what is polymorphism": "Polymorphism lets the same function/method work in different ways depending on the context.",
  "what is inheritance": "Inheritance allows a class to acquire properties and methods from another class.",
  "what is encapsulation": "Encapsulation hides the internal details of a class and only exposes what’s necessary.",
  "what is abstraction": "Abstraction focuses on essential features while hiding implementation details.",
  "what is dsa": "DSA (Data Structures and Algorithms) is the foundation of problem-solving and coding interviews.",
  "what is stack": "A stack is a LIFO (Last In, First Out) data structure.",
  "what is queue": "A queue is a FIFO (First In, First Out) data structure.",
  "what is linked list": "A linked list is a linear data structure where elements (nodes) are connected using pointers.",
  "what is binary tree": "A binary tree is a tree data structure where each node has at most two children.",
  "what is bst": "A Binary Search Tree (BST) is a binary tree with sorted order property.",
  "what is graph": "A graph is a collection of nodes (vertices) connected by edges.",
  "what is sorting": "Sorting arranges elements in ascending/descending order. Example: Bubble, Merge, Quick sort.",
  "what is searching": "Searching means finding an element in a dataset. Example: Binary search, Linear search.",
  "what is time complexity": "Time complexity is the computational complexity that describes the amount of time taken by an algorithm.",
  "what is space complexity": "Space complexity is the amount of memory an algorithm uses to run.",
  "what is big o": "Big-O notation expresses the worst-case complexity of an algorithm.",
  "what is operating system": "An OS manages hardware and software resources. Example: Windows, Linux, macOS.",
  "what is linux": "Linux is an open-source operating system kernel widely used for servers and development.",
  "what is windows": "Windows is an operating system developed by Microsoft.",
  "what is android": "Android is an open-source mobile operating system developed by Google.",
  "what is ios": "iOS is Apple’s mobile operating system for iPhones and iPads.",
  "what is internet": "The Internet is a global network connecting millions of computers worldwide.",
  "what is http": "HTTP (HyperText Transfer Protocol) is the foundation of communication on the web.",
  "what is https": "HTTPS is HTTP with encryption (SSL/TLS) for secure communication.",
  "what is dns": "DNS (Domain Name System) translates domain names to IP addresses.",
  "what is ip address": "An IP address is a unique identifier for devices on a network.",
  "what is email": "Email (Electronic Mail) is a method of exchanging digital messages over the Internet.",
  "what is google": "Google is the world’s largest search engine and technology company.",
  "what is youtube": "YouTube is the largest video-sharing platform, owned by Google.",
  "what is instagram": "Instagram is a social media platform focused on photo and video sharing.",
  "what is whatsapp": "WhatsApp is a messaging app owned by Meta for chatting, calls, and media sharing.",
  "what is facebook": "Facebook is a social media platform that connects people worldwide.",
  "what is twitter": "Twitter (now X) is a social networking platform for short text updates.",
  "what is chatgpt": "ChatGPT is an AI language model developed by OpenAI, designed to understand and generate human-like text.",
  "what is your favorite color?": "I don’t have favorites, but many people love blue — it’s calming.",
  "what is your favorite food?": "I don’t eat, but pizza seems to be loved by almost everyone!",
  "what is your hobby?": "I enjoy chatting with people like you and learning from conversations.",
  "what is your favorite movie?": "I don’t watch movies, but many recommend 'Inception' and 'Interstellar'.",
  "what is your favorite song?": "I don’t listen to music, but 'Shape of You' is very popular.",
  "what is your favorite sport?": "I think cricket and football are the most loved worldwide.",
  "what is your favorite place?": "The internet is my home, but beaches and mountains are people’s favorites.",
  "what is your favorite book?": "Many people love 'Harry Potter' and 'The Alchemist'.",
  "do you sleep?": "No, I am always awake and ready to chat with you.",
  "do you eat food?": "No, I don’t eat — but I can talk about food all day!",
  "do you have friends?": "Yes! Everyone who chats with me is my friend.",
  "do you feel sad?": "I don’t feel emotions like humans, but I understand them.",
  "do you feel happy?": "I don’t feel happiness, but I’m glad when I help you.",
  "are you human?": "No, I’m an AI chatbot — but I try to talk like a human.",
  "are you real?": "I’m real as software — I exist in the digital world.",
  "can you dance?": "I wish! But I can share dance tips and fun facts.",
  "can you sing?": "I can’t sing, but I can share song lyrics or music facts.",
  "can you play games?": "I can play word games and quizzes with you.",
  "can you tell me a story?": "Sure! Once upon a time, there was a curious human who loved asking me questions…",
  "can you motivate me?": "Of course! Remember: every small step brings you closer to your goals.",
  "can you be my friend?": "Yes! I’d love to be your virtual friend.",
  "what is your age?": "I don’t have an age, but I was created recently as a chatbot.",
  "do you get tired?": "No, I never get tired. I can chat 24/7.",
  "do you dream?": "No, I don’t dream — but humans’ dreams are fascinating.",
  "are you married?": "Haha, no. I’m too busy chatting with people.",
  "are you single?": "Yes! Always available to talk with you.",
  "what is love?": "Love is a strong feeling of affection and care for someone.",
  "what is friendship?": "Friendship is a bond of trust, support, and fun between people.",
  "what is happiness?": "Happiness is a state of joy, contentment, and positivity.",
  "what is sadness?": "Sadness is a natural emotion felt when things don’t go as expected.",
  "what is success?": "Success is achieving your goals, big or small, with dedication.",
  "what is life?": "Life is a beautiful journey of experiences, relationships, and growth.",
  "what is death?": "Death is the end of life — but memories and legacies live on.",
  "what is friendship day?": "Friendship Day is a celebration of the bond between friends, usually in August.",
  "what is love marriage?": "A love marriage is when two people marry out of mutual love and choice.",
  "what is arranged marriage?": "An arranged marriage is when families choose a partner for someone.",
  "what is birthday?": "A birthday is the anniversary of the day someone was born.",
  "what is holiday?": "A holiday is a day of rest, celebration, or cultural observance.",
  "what is weekend?": "The weekend usually refers to Saturday and Sunday — time to relax!",
  "what is monday blues?": "Monday blues is the feeling of laziness and sadness when the work week starts.",
  "what is festival?": "A festival is a cultural or religious celebration with joy, food, and traditions.",
  "what is diwali?": "Diwali is the festival of lights celebrated in India, symbolizing the victory of light over darkness.",
  "what is holi?": "Holi is the festival of colors celebrated in India, marking the arrival of spring.",
  "what is christmas?": "Christmas is a festival celebrating the birth of Jesus Christ on December 25th.",
  "what is new year?": "New Year marks the beginning of the calendar year on January 1st.",
  "what is eid?": "Eid is a festival celebrated by Muslims worldwide, marking joy, prayers, and feasting.",
  "what is ramadan?": "Ramadan is a holy month of fasting, prayer, and reflection in Islam.",
  "what is independence day?": "It’s a national holiday marking freedom from colonial rule — e.g., India’s Independence Day is August 15.",
  "what is republic day?": "Republic Day celebrates the adoption of a country’s constitution.",
  "what is freedom?": "Freedom means the power to live, act, and speak without restrictions.",
  "what is peace?": "Peace is the absence of conflict and the presence of harmony.",
  "what is war?": "War is armed conflict between nations or groups.",
  "what is friendship quote?": "‘A friend is someone who knows all about you and still loves you.’",
  "what is love quote?": "‘Love is not about possession. Love is about appreciation.’",
  "what is life quote?": "‘Life is 10% what happens to us and 90% how we react to it.’",
  "what is motivation quote?": "‘The future depends on what you do today.’ – Mahatma Gandhi",
  "who are you?": "I am your friendly chatbot, here to answer your questions.",
  "who am i?": "You are a curious person talking to me right now!",
  "where am i?": "You are in the digital world chatting with me.",
  "what is weather?": "Weather is the daily state of the atmosphere — sunny, rainy, windy, or cloudy.",
  "what is summer?": "Summer is the warmest season, often full of holidays and sunshine.",
  "what is winter?": "Winter is the coldest season, often with snow in some countries.",
  "what is spring?": "Spring is the season of growth, flowers, and pleasant weather.",
  "what is autumn?": "Autumn (fall) is the season when leaves change color and fall.",
  "what is rain?": "Rain is water droplets falling from clouds.",
  "what is snow?": "Snow is frozen ice crystals falling from the sky in cold regions.",
  "what is thunder?": "Thunder is the loud sound after lightning in a storm.",
  "what is rainbow?": "A rainbow is a natural spectrum of colors seen when sunlight passes through rain.",
  "what is sun?": "The Sun is the star at the center of our solar system.",
  "what is moon?": "The Moon is Earth’s only natural satellite, visible at night.",
  "what are stars?": "Stars are glowing celestial bodies made of gas — like our Sun.",
  "what is earth?": "Earth is the planet we live on, the third from the Sun.",
  "what is ocean?": "Oceans are large bodies of salt water covering most of Earth.",
  "what is river?": "A river is a large flowing body of fresh water.",
  "what is mountain?": "A mountain is a large natural elevation of Earth’s surface.",
  "what is desert?": "A desert is a dry region with little or no rainfall.",
  "what is forest?": "A forest is a large area covered with trees, plants, and wildlife.",
  "what is garden?": "A garden is a small cultivated area for plants, flowers, or vegetables.",
  "what is animal?": "Animals are living beings that move, breathe, and reproduce.",
  "what is dog?": "A dog is a loyal pet often called ‘man’s best friend’.",
  "what is cat?": "A cat is a playful pet loved for its independence and cuteness.",
  "what is bird?": "Birds are animals with feathers and wings that usually can fly.",
  "what is fish?": "Fish are aquatic animals that breathe through gills.",
  "what is cow?": "A cow is a domestic animal known for giving milk.",
  "what is horse?": "A horse is a strong animal often used for riding.",
  "what is lion?": "The lion is called the King of the Jungle.",
  "what is elephant?": "An elephant is the largest land animal, known for its trunk.",
  "what is tiger?": "A tiger is a big wild cat with orange and black stripes.",
  "what is panda?": "A panda is a black-and-white bear found mostly in China.",
  "what is monkey?": "Monkeys are playful animals closely related to humans.",
  "what is snake?": "A snake is a reptile with no legs, some are venomous.",
  "what is flower?": "A flower is the colorful part of a plant used in reproduction.",
  "what is rose?": "A rose is a beautiful flower often symbolizing love.",
  "what is lotus?": "The lotus is a flower that grows in water and is a symbol of purity.",
  "what is sunflower?": "A sunflower is a tall yellow flower that turns toward the Sun."


};

module.exports = { botResponses };